language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
script:
  - npm run build
deploy:
  provider: npm
  email: "xxx@xxx.xxx"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    branch: master
